---

- name: logical volume {{ fs_mountpoint }}
  lvol:
    lv: "{{ fs_lv_name }}"
    vg: "{{ fs_vg_name }}"
    size: "{{ fs_size }}"
    shrink: no

# dashes in vg and lv names are doubled
#
- name: filesystem {{ fs_mountpoint }}
  filesystem:
    dev: /dev/mapper/{{ fs_vg_name|replace("-","--") }}-{{ fs_lv_name|replace("-","--") }}
    fstype: "{{ fs_fstype }}"

- name: mount point
  file:
    path: "{{ fs_mountpoint }}"
    state: directory

# dashes in vg and lv names are doubled
#
- name: mount {{ fs_mountpoint }}
  mount:
    src: /dev/mapper/{{ fs_vg_name|replace("-","--") }}-{{ fs_lv_name|replace("-","--") }}
    path: "{{ fs_mountpoint }}"
    state: mounted
    fstype: "{{ fs_fstype }}"
    opts: "{{ fs_mountoptions }}"

- name: selinux type of {{ fs_mountpoint }}
  file:
    path: "{{ fs_mountpoint }}"
    state: directory
    setype: "{{ fs_selinux_type }}"
  when: fs_selinux_type is defined

# dashes in vg and lv names are doubled
#
- name: resize {{ fs_mountpoint }}
  filesystem:
    dev: /dev/mapper/{{ fs_vg_name|replace("-","--") }}-{{ fs_lv_name|replace("-","--") }}
    fstype: "{{ fs_fstype }}"
    resizefs: yes
